; Generated by scientific-dsl → LLVM IR
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare double @llvm.pow.f64(double, double)
declare void  @__dsl_store(double, i8*)
declare double @__dsl_load(i8*)

define double @heat_diffusion(double %u, double %alpha, double %dx, double %dt) {
entry:
  %r1 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.alpha, i32 0, i32 0))
  %r2 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.dx, i32 0, i32 0))
  %r3 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.dt, i32 0, i32 0))
  call void @__dsl_store(double 2.560000e2, i8* getelementptr ([64 x i8], [64 x i8]* @.nx, i32 0, i32 0))
  %r4 = fmul double %r1, %r3
  %r5 = fmul double %r2, %r2
  %r6 = fdiv double %r4, %r5
  call void @__dsl_store(double %r6, i8* getelementptr ([64 x i8], [64 x i8]* @.r, i32 0, i32 0))
  ; tensor[0.000000e0] → %r7
  call void @__dsl_store(double %r7, i8* getelementptr ([64 x i8], [64 x i8]* @.u_next, i32 0, i32 0))
  br label %bb1
loop_header_i:
  %r8 = phi double [1.0, %bb0], [%r21, %bb2]
  %r9 = fcmp olt double %r8, 255.0
  br i1 %r9, label %bb2, label %bb3
loop_body_i:
  %r10 = fadd double %r8, 1.0
  %r11 = ; index %r0 [%r10]
  %r12 = ; index %r0 [%r8]
  %r13 = fmul double 2.000000e0, %r12
  %r14 = fsub double %r11, %r13
  %r15 = fsub double %r8, 1.0
  %r16 = ; index %r0 [%r15]
  %r17 = fadd double %r14, %r16
  %r18 = fmul double %r6, %r17
  %r19 = ; index %r0 [%r8]
  %r20 = fadd double %r18, %r19
  call void @__dsl_store(double %r20, i8* getelementptr ([64 x i8], [64 x i8]* @.u_next, i32 0, i32 0))
  br label %bb1
loop_exit_i:
  ret double %r20
}

define double @total_kinetic_energy(double %m, double %vx, double %vy, double %vz) {
entry:
  call void @__dsl_store(double 0.000000e0, i8* getelementptr ([64 x i8], [64 x i8]* @.ke, i32 0, i32 0))
  call void @__dsl_store(double 1.024000e3, i8* getelementptr ([64 x i8], [64 x i8]* @.n, i32 0, i32 0))
  br label %bb1
loop_header_i:
  %r4 = phi double [0.0, %bb0], [%r17, %bb2]
  %r5 = fcmp olt double %r4, 1024.0
  br i1 %r5, label %bb2, label %bb3
loop_body_i:
  %r6 = ; index %r1 [%r4]
  %r7 = call double @llvm.pow.f64(double %r6, double 2.000000e0)
  %r8 = ; index %r2 [%r4]
  %r9 = call double @llvm.pow.f64(double %r8, double 2.000000e0)
  %r10 = fadd double %r7, %r9
  %r11 = ; index %r3 [%r4]
  %r12 = call double @llvm.pow.f64(double %r11, double 2.000000e0)
  %r13 = fadd double %r10, %r12
  call void @__dsl_store(double %r13, i8* getelementptr ([64 x i8], [64 x i8]* @.v2, i32 0, i32 0))
  %r14 = fmul double 5.000000e-1, %r0
  %r15 = fmul double %r14, %r13
  %r16 = fadd double 0.000000e0, %r15
  call void @__dsl_store(double %r16, i8* getelementptr ([64 x i8], [64 x i8]* @.ke, i32 0, i32 0))
  br label %bb1
loop_exit_i:
  ret double %r16
}

define double @gravitational_potential(double %G, double %m1, double %m2, double %r) {
entry:
  %r0 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.G, i32 0, i32 0))
  %r1 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.m1, i32 0, i32 0))
  %r2 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.m2, i32 0, i32 0))
  %r3 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.r, i32 0, i32 0))
  %r4 = fneg double %r0
  %r5 = fmul double %r4, %r1
  %r6 = fmul double %r5, %r2
  %r7 = fdiv double %r6, %r3
  ret double %r7
}

define double @rms_velocity(double %kb, double %T, double %m) {
entry:
  %r0 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.kb, i32 0, i32 0))
  %r1 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.T, i32 0, i32 0))
  %r2 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.m, i32 0, i32 0))
  %r3 = fmul double 3.000000e0, %r0
  %r4 = fmul double %r3, %r1
  %r5 = fdiv double %r4, %r2
  %r6 = call double @sqrt(double %r5)
  ret double %r6
}

define double @lorenz_step(double %x, double %y, double %z, double %sigma, double %rho, double %beta, double %dt) {
entry:
  %r0 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.x, i32 0, i32 0))
  %r1 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.y, i32 0, i32 0))
  %r2 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.z, i32 0, i32 0))
  %r3 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.sigma, i32 0, i32 0))
  %r4 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.rho, i32 0, i32 0))
  %r5 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.beta, i32 0, i32 0))
  %r6 = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.dt, i32 0, i32 0))
  %r7 = fsub double %r1, %r0
  %r8 = fmul double %r3, %r7
  %r9 = fmul double %r8, %r6
  call void @__dsl_store(double %r9, i8* getelementptr ([64 x i8], [64 x i8]* @.dx, i32 0, i32 0))
  %r10 = fsub double %r4, %r2
  %r11 = fmul double %r0, %r10
  %r12 = fsub double %r11, %r1
  %r13 = fmul double %r12, %r6
  call void @__dsl_store(double %r13, i8* getelementptr ([64 x i8], [64 x i8]* @.dy, i32 0, i32 0))
  %r14 = fmul double %r0, %r1
  %r15 = fmul double %r5, %r2
  %r16 = fsub double %r14, %r15
  %r17 = fmul double %r16, %r6
  call void @__dsl_store(double %r17, i8* getelementptr ([64 x i8], [64 x i8]* @.dz, i32 0, i32 0))
  %r18 = fadd double %r0, %r9
  %r19 = fadd double %r1, %r13
  %r20 = fadd double %r2, %r17
  ; tensor[%r18, %r19, %r20] → %r21
  ret double %r21
}

define double @frobenius_norm(double %A, double %n) {
entry:
  call void @__dsl_store(double 0.000000e0, i8* getelementptr ([64 x i8], [64 x i8]* @.acc, i32 0, i32 0))
  br label %bb1
loop_header_i:
  %r2 = phi double [0.0, %bb0], [%r7, %bb2]
  %r3 = fcmp olt double %r2, 1024.0
  br i1 %r3, label %bb2, label %bb3
loop_body_i:
  %r4 = ; index %r0 [%r2]
  %r5 = call double @llvm.pow.f64(double %r4, double 2.000000e0)
  %r6 = fadd double 0.000000e0, %r5
  call void @__dsl_store(double %r6, i8* getelementptr ([64 x i8], [64 x i8]* @.acc, i32 0, i32 0))
  br label %bb1
loop_exit_i:
  %r8 = call double @sqrt(double %r6)
  ret double %r8
}

