// Generated by scientific-dsl → CUDA C
#include <cuda_runtime.h>
#include <math.h>
#include <stdio.h>

// ── Helper macros ────────────────────────────────────────
#define CUDA_CHECK(e) { cudaError_t _e=(e); if(_e) { fprintf(stderr,"CUDA error %s\n",cudaGetErrorString(_e)); exit(1); } }

__global__ void heat_diffusion(double* u, double alpha, double dx, double dt) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    // ── SSA body ────────────────────────────────────────
    // block: entry
    double _r1 = __dsl_alpha[tid];
    double _r2 = __dsl_dx[tid];
    double _r3 = __dsl_dt[tid];
    __dsl_nx[tid] = 256.000000;
    double _r4 = _r1 * _r3;
    double _r5 = _r2 * _r2;
    double _r6 = _r4 / _r5;
    __dsl_r[tid] = _r6;
    /* tensor _r7 = [0.000000] */
    __dsl_u_next[tid] = _r7;
    goto block_1;
    // block: loop_header_i
    /* phi _r8 = (block0: 1), (block2: _r21) */
    /* unhandled instr */
    if ((int)_r9) goto block_2; else goto block_3;
    // block: loop_body_i
    double _r10 = _r8 + 1;
    double _r11 = _r0[(int)_r10];
    double _r12 = _r0[(int)_r8];
    double _r13 = 2.000000 * _r12;
    double _r14 = _r11 - _r13;
    double _r15 = _r8 - 1;
    double _r16 = _r0[(int)_r15];
    double _r17 = _r14 + _r16;
    double _r18 = _r6 * _r17;
    double _r19 = _r0[(int)_r8];
    double _r20 = _r18 + _r19;
    __dsl_u_next[tid] = _r20;
    goto block_1;
    // block: loop_exit_i
    /* return _r20 */
}

__global__ void total_kinetic_energy(double m, double* vx, double* vy, double* vz) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    // ── SSA body ────────────────────────────────────────
    // block: entry
    __dsl_ke[tid] = 0.000000;
    __dsl_n[tid] = 1024.000000;
    goto block_1;
    // block: loop_header_i
    /* phi _r4 = (block0: 0), (block2: _r17) */
    /* unhandled instr */
    if ((int)_r5) goto block_2; else goto block_3;
    // block: loop_body_i
    double _r6 = _r1[(int)_r4];
    double _r7 = pow(_r6, 2.000000);
    double _r8 = _r2[(int)_r4];
    double _r9 = pow(_r8, 2.000000);
    double _r10 = _r7 + _r9;
    double _r11 = _r3[(int)_r4];
    double _r12 = pow(_r11, 2.000000);
    double _r13 = _r10 + _r12;
    __dsl_v2[tid] = _r13;
    double _r14 = 0.500000 * _r0;
    double _r15 = _r14 * _r13;
    double _r16 = 0.000000 + _r15;
    __dsl_ke[tid] = _r16;
    goto block_1;
    // block: loop_exit_i
    /* return _r16 */
}

__global__ void gravitational_potential(double G, double m1, double m2, double r) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    // ── SSA body ────────────────────────────────────────
    // block: entry
    double _r0 = __dsl_G[tid];
    double _r1 = __dsl_m1[tid];
    double _r2 = __dsl_m2[tid];
    double _r3 = __dsl_r[tid];
    double _r4 = -_r0;
    double _r5 = _r4 * _r1;
    double _r6 = _r5 * _r2;
    double _r7 = _r6 / _r3;
    /* return _r7 */
}

__global__ void rms_velocity(double kb, double T, double m) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    // ── SSA body ────────────────────────────────────────
    // block: entry
    double _r0 = __dsl_kb[tid];
    double _r1 = __dsl_T[tid];
    double _r2 = __dsl_m[tid];
    double _r3 = 3.000000 * _r0;
    double _r4 = _r3 * _r1;
    double _r5 = _r4 / _r2;
    double _r6 = sqrt(_r5);
    /* return _r6 */
}

__global__ void lorenz_step(double x, double y, double z, double sigma, double rho, double beta, double dt) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    // ── SSA body ────────────────────────────────────────
    // block: entry
    double _r0 = __dsl_x[tid];
    double _r1 = __dsl_y[tid];
    double _r2 = __dsl_z[tid];
    double _r3 = __dsl_sigma[tid];
    double _r4 = __dsl_rho[tid];
    double _r5 = __dsl_beta[tid];
    double _r6 = __dsl_dt[tid];
    double _r7 = _r1 - _r0;
    double _r8 = _r3 * _r7;
    double _r9 = _r8 * _r6;
    __dsl_dx[tid] = _r9;
    double _r10 = _r4 - _r2;
    double _r11 = _r0 * _r10;
    double _r12 = _r11 - _r1;
    double _r13 = _r12 * _r6;
    __dsl_dy[tid] = _r13;
    double _r14 = _r0 * _r1;
    double _r15 = _r5 * _r2;
    double _r16 = _r14 - _r15;
    double _r17 = _r16 * _r6;
    __dsl_dz[tid] = _r17;
    double _r18 = _r0 + _r9;
    double _r19 = _r1 + _r13;
    double _r20 = _r2 + _r17;
    /* tensor _r21 = [_r18, _r19, _r20] */
    /* return _r21 */
}

__global__ void frobenius_norm(double* A, double n) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    // ── SSA body ────────────────────────────────────────
    // block: entry
    __dsl_acc[tid] = 0.000000;
    goto block_1;
    // block: loop_header_i
    /* phi _r2 = (block0: 0), (block2: _r7) */
    /* unhandled instr */
    if ((int)_r3) goto block_2; else goto block_3;
    // block: loop_body_i
    double _r4 = _r0[(int)_r2];
    double _r5 = pow(_r4, 2.000000);
    double _r6 = 0.000000 + _r5;
    __dsl_acc[tid] = _r6;
    goto block_1;
    // block: loop_exit_i
    double _r8 = sqrt(_r6);
    /* return _r8 */
}

