// src/codegen.rs — Backend Code Generation
//
// Three targets:
//   1. LLVM IR (textual) — portable; feed to `llc` for native or PTX
//   2. CUDA C  — NVIDIA GPU kernels; feed to nvcc
//   3. MLIR    — placeholder dialect output for future MLIR pipeline
//
// All targets operate on the SSA IrModule produced by ir::lower_program.

use crate::ast::TypeAnnotation;
use crate::ir::*;
use crate::errors::DslError;

// ─────────────────────────────────────────────────────────────────────────────
// Target selector
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub enum Target {
    LlvmIr,
    CudaC,
    MlirDialect,
}

impl std::str::FromStr for Target {
    type Err = DslError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "llvm" | "llvmir" => Ok(Target::LlvmIr),
            "cuda"            => Ok(Target::CudaC),
            "mlir"            => Ok(Target::MlirDialect),
            other => Err(DslError::CodegenError(format!("Unknown target: {}", other))),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Dispatch
// ─────────────────────────────────────────────────────────────────────────────

pub fn generate(module: &IrModule, target: &Target) -> Result<String, DslError> {
    match target {
        Target::LlvmIr      => Ok(LlvmGen::new().emit_module(module)),
        Target::CudaC       => Ok(CudaGen::new().emit_module(module)),
        Target::MlirDialect => Ok(MlirGen::new().emit_module(module)),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ① LLVM IR Generator
// ─────────────────────────────────────────────────────────────────────────────

struct LlvmGen {
    out: String,
}

impl LlvmGen {
    fn new() -> Self { LlvmGen { out: String::new() } }

    fn w(&mut self, s: impl AsRef<str>) { self.out.push_str(s.as_ref()); self.out.push('\n'); }

    fn emit_module(mut self, module: &IrModule) -> String {
        self.w("; Generated by scientific-dsl → LLVM IR");
        self.w("target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"");
        self.w("target triple = \"x86_64-unknown-linux-gnu\"");
        self.w("");
        self.w("declare double @llvm.pow.f64(double, double)");
        self.w("declare void  @__dsl_store(double, i8*)");
        self.w("declare double @__dsl_load(i8*)");
        self.w("");

        for func in &module.functions {
            self.emit_function(func);
        }

        if !module.main.is_empty() {
            let main_fn = IrFunction {
                name:   "__main__".to_string(),
                params: vec![],
                ret_ty: TypeAnnotation::F64,
                blocks: module.main.clone(),
            };
            self.emit_function(&main_fn);
        }
        self.out
    }

    fn emit_function(&mut self, func: &IrFunction) {
        let params: Vec<String> = func.params.iter()
            .map(|(n, _)| format!("double %{}", n))
            .collect();
        self.w(format!("define double @{}({}) {{", func.name, params.join(", ")));

        for (idx, block) in func.blocks.iter().enumerate() {
            self.w(format!("{}:", block.label));
            for instr in &block.instructions {
                self.emit_instr(instr);
            }
            self.emit_term(&block.terminator);
        }
        self.w("}");
        self.w("");
    }

    fn emit_instr(&mut self, instr: &Instruction) {
        let line = match instr {
            Instruction::Add { dest, lhs, rhs } =>
                format!("  {} = fadd double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Sub { dest, lhs, rhs } =>
                format!("  {} = fsub double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Mul { dest, lhs, rhs } =>
                format!("  {} = fmul double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Div { dest, lhs, rhs } =>
                format!("  {} = fdiv double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Neg { dest, src } =>
                format!("  {} = fneg double {}", llreg(dest), llval(src)),
            Instruction::Pow { dest, base, exp } =>
                format!("  {} = call double @llvm.pow.f64(double {}, double {})", llreg(dest), llval(base), llval(exp)),
            Instruction::Lt { dest, lhs, rhs } =>
                format!("  {} = fcmp olt double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Gt { dest, lhs, rhs } =>
                format!("  {} = fcmp ogt double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Le { dest, lhs, rhs } =>
                format!("  {} = fcmp ole double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Ge { dest, lhs, rhs } =>
                format!("  {} = fcmp oge double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Eq { dest, lhs, rhs } =>
                format!("  {} = fcmp oeq double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Ne { dest, lhs, rhs } =>
                format!("  {} = fcmp one double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Call { dest, func, args } => {
                let arg_s: Vec<_> = args.iter().map(|a| format!("double {}", llval(a))).collect();
                format!("  {} = call double @{}({})", llreg(dest), func, arg_s.join(", "))
            }
            Instruction::Load { dest, name } =>
                format!("  {} = call double @__dsl_load(i8* getelementptr ([64 x i8], [64 x i8]* @.{}, i32 0, i32 0))", llreg(dest), name),
            Instruction::Store { src, name } =>
                format!("  call void @__dsl_store(double {}, i8* getelementptr ([64 x i8], [64 x i8]* @.{}, i32 0, i32 0))", llval(src), name),
            Instruction::Phi { dest, incoming } => {
                let parts: Vec<_> = incoming.iter()
                    .map(|(v, b)| format!("[{}, %bb{}]", llval(v), b))
                    .collect();
                format!("  {} = phi double {}", llreg(dest), parts.join(", "))
            }
            Instruction::BuildTensor { dest, elems } =>
                format!("  ; tensor[{}] → {}", elems.iter().map(llval).collect::<Vec<_>>().join(", "), llreg(dest)),
            Instruction::Index { dest, base, idx } =>
                format!("  {} = ; index {} [{}]", llreg(dest), llval(base), llval(idx)),
            Instruction::Mod  { dest, lhs, rhs } =>
                format!("  {} = frem double {}, {}", llreg(dest), llval(lhs), llval(rhs)),
            Instruction::Comment(s) =>
                format!("  ; {}", s),
        };
        self.w(line);
    }

    fn emit_term(&mut self, term: &Terminator) {
        let line = match term {
            Terminator::Jump(b)   => format!("  br label %bb{}", b),
            Terminator::Return(v) => format!("  ret double {}", llval(v)),
            Terminator::CondJump { cond, true_block, false_block } =>
                format!("  br i1 {}, label %bb{}, label %bb{}", llval(cond), true_block, false_block),
            Terminator::Unreachable => "  unreachable".to_string(),
        };
        self.w(line);
    }
}

fn llreg(r: &Register) -> String { format!("%r{}", r.0) }
fn llval(v: &Value) -> String {
    match v {
        Value::Reg(r)      => llreg(r),
        Value::ConstF64(f) => format!("{:.6e}", f),
        Value::ConstI64(i) => format!("{}.0", i),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ② CUDA C Generator
// ─────────────────────────────────────────────────────────────────────────────

struct CudaGen { out: String }

impl CudaGen {
    fn new() -> Self { CudaGen { out: String::new() } }

    fn w(&mut self, s: impl AsRef<str>) { self.out.push_str(s.as_ref()); self.out.push('\n'); }

    fn emit_module(mut self, module: &IrModule) -> String {
        self.w("// Generated by scientific-dsl → CUDA C");
        self.w("#include <cuda_runtime.h>");
        self.w("#include <math.h>");
        self.w("#include <stdio.h>");
        self.w("");
        self.w("// ── Helper macros ────────────────────────────────────────");
        self.w("#define CUDA_CHECK(e) { cudaError_t _e=(e); if(_e) { fprintf(stderr,\"CUDA error %s\\n\",cudaGetErrorString(_e)); exit(1); } }");
        self.w("");

        for func in &module.functions {
            self.emit_kernel(func);
        }

        // Emit host launcher for main
        if !module.main.is_empty() {
            self.w("// ── Host entry ───────────────────────────────────────");
            self.w("int main(int argc, char** argv) {");
            self.w("    // TODO: allocate device memory, set grid/block dims, launch kernels");
            self.w("    return 0;");
            self.w("}");
        }
        self.out
    }

    fn emit_kernel(&mut self, func: &IrFunction) {
        let params: Vec<String> = func.params.iter()
            .map(|(n, ty)| format!("{} {}", cuda_ty(ty), n))
            .collect();
        self.w(format!("__global__ void {}({}) {{", func.name, params.join(", ")));
        self.w("    int tid = blockIdx.x * blockDim.x + threadIdx.x;");
        self.w("    // ── SSA body ────────────────────────────────────────");
        for block in &func.blocks {
            self.w(format!("    // block: {}", block.label));
            for instr in &block.instructions {
                self.w(format!("    {}", cuda_instr(instr)));
            }
            self.w(format!("    {}", cuda_term(&block.terminator)));
        }
        self.w("}");
        self.w("");
    }
}

fn cuda_ty(ty: &TypeAnnotation) -> &'static str {
    match ty {
        TypeAnnotation::F64    => "double",
        TypeAnnotation::F32    => "float",
        TypeAnnotation::Tensor => "double*",
        _                      => "double",
    }
}

fn cuda_val(v: &Value) -> String {
    match v {
        Value::Reg(r)      => format!("_r{}", r.0),
        Value::ConstF64(f) => format!("{:.6}", f),
        Value::ConstI64(i) => format!("{}", i),
    }
}

fn cuda_instr(i: &Instruction) -> String {
    match i {
        Instruction::Add { dest, lhs, rhs } =>
            format!("double {} = {} + {};",  cuda_val(&Value::Reg(dest.clone())), cuda_val(lhs), cuda_val(rhs)),
        Instruction::Sub { dest, lhs, rhs } =>
            format!("double {} = {} - {};",  cuda_val(&Value::Reg(dest.clone())), cuda_val(lhs), cuda_val(rhs)),
        Instruction::Mul { dest, lhs, rhs } =>
            format!("double {} = {} * {};",  cuda_val(&Value::Reg(dest.clone())), cuda_val(lhs), cuda_val(rhs)),
        Instruction::Div { dest, lhs, rhs } =>
            format!("double {} = {} / {};",  cuda_val(&Value::Reg(dest.clone())), cuda_val(lhs), cuda_val(rhs)),
        Instruction::Pow { dest, base, exp } =>
            format!("double {} = pow({}, {});", cuda_val(&Value::Reg(dest.clone())), cuda_val(base), cuda_val(exp)),
        Instruction::Neg { dest, src } =>
            format!("double {} = -{};", cuda_val(&Value::Reg(dest.clone())), cuda_val(src)),
        Instruction::Call { dest, func, args } => {
            let arg_s: Vec<_> = args.iter().map(cuda_val).collect();
            format!("double {} = {}({});", cuda_val(&Value::Reg(dest.clone())), func, arg_s.join(", "))
        }
        Instruction::Load { dest, name } =>
            format!("double {} = __dsl_{}[tid];", cuda_val(&Value::Reg(dest.clone())), name),
        Instruction::Store { src, name } =>
            format!("__dsl_{}[tid] = {};", name, cuda_val(src)),
        Instruction::Index { dest, base, idx } =>
            format!("double {} = {}[(int){}];", cuda_val(&Value::Reg(dest.clone())), cuda_val(base), cuda_val(idx)),
        Instruction::BuildTensor { dest, elems } => {
            let e: Vec<_> = elems.iter().map(cuda_val).collect();
            format!("/* tensor {} = [{}] */", cuda_val(&Value::Reg(dest.clone())), e.join(", "))
        }
        Instruction::Phi { dest, incoming } => {
            let parts: Vec<_> = incoming.iter()
                .map(|(v, b)| format!("(block{}: {})", b, cuda_val(v)))
                .collect();
            format!("/* phi {} = {} */", cuda_val(&Value::Reg(dest.clone())), parts.join(", "))
        }
        Instruction::Comment(s) => format!("// {}", s),
        _ => format!("/* unhandled instr */"),
    }
}

fn cuda_term(t: &Terminator) -> String {
    match t {
        Terminator::Return(v)    => format!("/* return {} */", cuda_val(v)),
        Terminator::Jump(b)      => format!("goto block_{};", b),
        Terminator::CondJump { cond, true_block, false_block } =>
            format!("if ((int){}) goto block_{}; else goto block_{};", cuda_val(cond), true_block, false_block),
        Terminator::Unreachable  => "/* unreachable */".to_string(),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ③ MLIR Dialect stub
// ─────────────────────────────────────────────────────────────────────────────

struct MlirGen { out: String }

impl MlirGen {
    fn new() -> Self { MlirGen { out: String::new() } }
    fn w(&mut self, s: impl AsRef<str>) { self.out.push_str(s.as_ref()); self.out.push('\n'); }

    fn emit_module(mut self, module: &IrModule) -> String {
        self.w("// Generated by scientific-dsl → MLIR (arith + func dialects)");
        self.w("module @scientific_dsl {");
        for func in &module.functions {
            self.emit_func(func);
        }
        if !module.main.is_empty() {
            let main_fn = IrFunction {
                name:   "__main__".to_string(),
                params: vec![],
                ret_ty: crate::ast::TypeAnnotation::F64,
                blocks: module.main.clone(),
            };
            self.emit_func(&main_fn);
        }
        self.w("}");
        self.out
    }

    fn emit_func(&mut self, func: &IrFunction) {
        let params: Vec<String> = func.params.iter()
            .map(|(n, _)| format!("%{}: f64", n))
            .collect();
        self.w(format!("  func.func @{}({}) -> f64 {{", func.name, params.join(", ")));
        for block in &func.blocks {
            self.w(format!("  ^{}:", block.label));
            for instr in &block.instructions {
                self.w(format!("    {}", mlir_instr(instr)));
            }
            self.w(format!("    {}", mlir_term(&block.terminator)));
        }
        self.w("  }");
        self.w("");
    }
}

fn mlir_val(v: &Value) -> String {
    match v {
        Value::Reg(r)      => format!("%v{}", r.0),
        Value::ConstF64(f) => format!("{}  : f64", f),
        Value::ConstI64(i) => format!("{}  : i64", i),
    }
}

fn mlir_instr(i: &Instruction) -> String {
    match i {
        Instruction::Add { dest, lhs, rhs } =>
            format!("%v{} = arith.addf {}, {} : f64", dest.0, mlir_val(lhs), mlir_val(rhs)),
        Instruction::Sub { dest, lhs, rhs } =>
            format!("%v{} = arith.subf {}, {} : f64", dest.0, mlir_val(lhs), mlir_val(rhs)),
        Instruction::Mul { dest, lhs, rhs } =>
            format!("%v{} = arith.mulf {}, {} : f64", dest.0, mlir_val(lhs), mlir_val(rhs)),
        Instruction::Div { dest, lhs, rhs } =>
            format!("%v{} = arith.divf {}, {} : f64", dest.0, mlir_val(lhs), mlir_val(rhs)),
        Instruction::Call { dest, func, args } => {
            let arg_s: Vec<_> = args.iter().map(mlir_val).collect();
            format!("%v{} = func.call @{}({}) : ({}) -> f64", dest.0, func, arg_s.join(", "),
                    args.iter().map(|_| "f64").collect::<Vec<_>>().join(", "))
        }
        Instruction::Comment(s) => format!("// {}", s),
        _ => format!("// [unimplemented mlir instr]"),
    }
}

fn mlir_term(t: &Terminator) -> String {
    match t {
        Terminator::Return(v) => format!("func.return {} : f64", mlir_val(v)),
        Terminator::Jump(b)   => format!("cf.br ^bb{}", b),
        Terminator::CondJump { cond, true_block, false_block } =>
            format!("cf.cond_br {}, ^bb{}, ^bb{}", mlir_val(cond), true_block, false_block),
        Terminator::Unreachable => "// unreachable".to_string(),
    }
}
